### ISSUE TITLE
Interpolation issues in Briem Script and Briem Hand

### ISSUE THREAD

**Issue by Sayhone721** [SorkinType/Briem-Hand#1]
This recording was done in the variable Briem Script file.
https://user-images.githubusercontent.com/92538982/196037761-1c09f2fe-9834-4c9f-96cd-875b24232569.mp4

**Comment by EbenSorkin** [comment]
Thanks! This is fixed now.

**Comment by Sayhone721** [comment]
Thank you for fixing them, but you forgot some:
https://user-images.githubusercontent.com/92538982/217132650-4915deab-fa4b-4ede-abe6-f80777432f2c.mp4

**Comment by EbenSorkin** [comment]
The projects have been renamed now Script (connexted ) is now Hand And the old Hand (not connexted) is Print. The new Print will be derived from Hand. I fixed the reverse breve lc and UC tonight.

**Comment by EbenSorkin** [comment]
Thanks for the heads up!

**Comment by Sayhone721** [comment]
And there’s more…
https://user-images.githubusercontent.com/92538982/217393801-4a0aff59-d13f-40b3-ab21-62ce7c98e8ee.mov

**Comment by Sayhone721** [comment]
And these, but that’s it for now:
https://user-images.githubusercontent.com/92538982/217416864-48da2ad7-09ea-4786-94e7-8e130bde7e67.mp4

**Comment by Sayhone721** [comment]
And there’s this too:
https://user-images.githubusercontent.com/92538982/217962980-6dfc5146-cd53-44e3-9360-7c0321373d32.mp4

**Comment by EbenSorkin** [comment]
These are fixed now. Thank you!

**Comment by Sayhone721** [comment]
You’re welcome, but it’s still there (the glyph is `/eogonek`).
