### ISSUE TITLE
Interpolation Issues (2023-02-08)

### ISSUE THREAD

**Issue by kenmcd** [SorkinType/Briem-Hand#4]
Interpolation Issues (2023-02-08)
File: BriemHand.glyph - posted today 2023-02-08
Glyphs: /Oopen/oopen/ordmasculine/colon/apple/hryvnia/peso/minus/multiply/equal/infinity/partialdiff

![2023-02-08_10-59-44](https://user-images.githubusercontent.com/844920/217626791-6aadc9a9-f885-495c-aa3a-bd0aacf3f36d.gif)

**Comment by EbenSorkin** [comment]
I have pushed a fix for these now. Thanks very much!

**Comment by kenmcd** [comment]
Still a few issues with the new file.
/`ooopen` is still broken.
And found two more.
Glyphs: /idieresis/oopen/breveinvertedbelowcomb

![2023-02-08_12-04-51](https://user-images.githubusercontent.com/844920/217639978-2431fb83-fd73-4f9c-b5e5-4bae86205d48.gif)

**Comment by EbenSorkin** [comment]
I think these are fixed now

**Comment by kenmcd** [comment]
Hmmmm ... still seeing issues with `/idieresis` and `/oopen` in the source, and the fonts posted today (says posted 2 hours ago right now) - both the variable and the static fonts show the issues.

**Comment by EbenSorkin** [comment]
Maybe it’s a font cache issue? The font haven’t been renamed so depending
on methods that might be it. Still I’ll check again…
